title: ConstraintModelling.org
description: AI research group 
# https://github.com/CloudCannon/edition-jekyll-template
remote_theme: CloudCannon/edition-jekyll-template
header_pages:
  - index.md
  - team.md 
  - toolchain.md
  - projects.md 
  - publications.md
  - demos.md

feed_meta : ""