title: ConstraintModelling.org
description: AI research group 
# https://github.com/aterenin/minima-reboot/
remote_theme: aterenin/minima-reboot
header_pages:
  - index.md
  - team.md 
  - toolchain.md
  - projects.md 
  - publications.md
  - demos.md
