title: ConstraintModelling.org
description: CP tools
theme: minima
minima:
  skin: solarized-dark
header_pages:
  - index.md
  - contact.md
  - team.md 
  - toolchain.md
  - Projects: 
    + Topics:
        - CSPLib (ChrisJ/Oz?)
        - Athanor (ChrisJ/Pete/Nguyen?)
        - Streamliner (Oz/Patrick/Nguyen?)
        - Constraint Dominance Programming (Gok/Oz?)
        - Automated Instance Generation (Nguyen)
    + A blog post for each topic: 
        - brief description 
        - list of papers & talks
        - github repo
        - news
- Publications & Talks
- Demos (future addition)