title: ConstraintModelling.org
description: CP tools
theme: minima
minima:
  skin: solarized-dark
header_pages:
  - index.md
  - team.md 
  - toolchain.md
  - projects.md 
  - publications.md
  - demos.md