title: ConstraintModelling.org
description: CP tools
remote_theme: aterenin/minima-reboot
#minima:
#  skin: solarized-dark
header_pages:
  - index.md
  - contact.md
  - team.md 
  - toolchain.md
  - projects.md 
  - publications.md
  - demos.md 
